language: julia
os:
  - linux
  - osx

julia:
  - 1.1
  - nightly
notifications:

codecov: true
coveralls: true
after_success:
#  - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
#  - julia --project=coverage/ coverage/coverage.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/mkdocs.jl clean
        name: "Markdown/MkDocs"
        before_install:	pip install --upgrade pip #install: pip install --upgrade pip
        after_success: skip

    - script:
      - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - julia --project=docs/ --color=yes docs/make.jl clean
      name: "HTML"
      after_success: skip

    - script:
        - julia --project=docs/pdf/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/pdf/ --color=yes docs/pdf/make.jl clean
      name: "PDF"
      after_success: skip
      services: docker
