site_name:        GeoEfficiency.jl
repo_url:         https://github.com/DrKrar/ GeoEfficiency.jl
edit_uri: ""
site_description: Acurate geometrical efficiency calculator
site_author:      Mohamed E. Krar
remote_branch: gh-pages-MkDocs

theme: 
    name: readthedocs   #mkdocs
    highlightjs: true
    hljs_languages:
        - Julia

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - def_list
  - toc:
        permalink: True
  #- mdx_math
docs_dir: 'docs/MarkDown/'

nav:
  - Home: Guid.md
  - Mauual: 
    - About: manual/GeoEfficiency.md
    - Physics Model: manual/Physics_Model.md
    - Calculations: manual/Calculations.md
    - Output Interface: manual/Output_Interface.md
    - Input Batch: manual/Input_Batch.md
  - Development: manual/Development.md
  - Index: list.md

plugins:
  - search

copyright: Copyright &copy; 2019
